ActiveSupport Instrumentation API support
yhirano55/approval pull request #20
Opened 2018-05-07 10:07 UTC by tsugimoto

Adds ActiveSupport notification events.

#### Events

- `request.approval`
- `cancel.approval`
- `reject.approval`
- `approve.approval`
- `approve_with_execute.approval`
- `execute.approval`

#### Event parameters

- `payload[:request]` `Approval::Request` object
- `payload[:user]` User object
- `payload[:comment]` `Approval::Comment` object, if present

2018-05-08 01:54 UTC, yhirano55 requested changes
It looks not DRY. Please Modulize like this, and include each based model.

```ruby
module Approval
  module Notifiable
    extend ActiveSupport::Concern

    private

    def instrument(operation, payload = {}, &block)
      ActiveSupport::Notifications.instrument("#{operation}.approval", payload, &block)
    end
  end
end
```

And you can implement form like this:

```ruby
module Approval
  module RequestForm
    class Create < Base
      private

        def prepare
          instrument "create", user: user, reason: reason, request: request do |payload|
            ::Approval::Request.transaction do
              payload[:comment] = request.comments.new(user_id: user.id, content: reason)
              # You can read items from the request object, so it doesn't need to set to payload.
              Array(records).each do |record|
                request.items.new(
                  event: "create",
                  resource_type: record.class.to_s,
                  params: record.create_params_for_approval,
                )
              end
              yield(request)
            end
          end
        end
    end
  end
end
```

2018-05-09 05:46 UTC, tsugimoto commented
Fixed!

2018-05-09 06:04 UTC, yhirano55 commented on app/models/approval/request_form/update.rb
> +              payload[:request] = request
Let's remove this.

2018-05-09 06:13 UTC, yhirano55 approved these changes

2018-05-09 06:13 UTC, merged